(define (problem cut-cucumber-1)
(:domain cut-cucumber)
(:objects
    <insert_objects>
)
(:init
    (hand_empty r_hand)  ;put your assumptions about the start of a session here
    (hand_empty l_hand)
    (stored bread1)
    (stored_in bread1 cupboard1)
    (stored plastic_paper_bag1)
    (stored_in plastic_paper_bag1 cupboard1)
    (stored sponge1)
    (stored_in sponge1 g_drawer1)
    (stored peeler1)
    (stored_in peeler1 drawer1)
    (stored cucumber1)
    (stored_in cucumber1 fridge1)
    (stored cuttingboard1)
    (stored_in cuttingboard1 drawer1)
    (stored knife1)
    (stored_in knife1 drawer1)
    (stored plate1)
    (stored_in plate1 cupboard1)
    (stored spice_shaker1)
    (stored_in spice_shaker1 spice_holder1)
    (stored plastic_bag1)
    (stored_in plastic_bag1 cupboard1)
    (stored bowl1)
    (stored_in bowl1 cupboard1)
    (stored spice1)
    (stored_in spice1 spice_holder1)
    <insert_class_memberships>
)
(:goal (and
(goaldummy)
))
)
