(define (problem cut-cucumber-1)
(:domain cut-cucumber)
(:objects
    <insert_objects>
)
(:init
    (hand_empty righthand_1)  ;put your assumptions about the start of a session here
    (hand_empty lefthand_1)
(stored salad_1)
(stored_in toast_3 top_cabinet_1)
(stored_in large_bowl_1 large_bowl_2)
(stored ladle_2)
(stored deep_pan_1)
(stored_in carrot_1 fridge_1)
(stored lime_1)
(stored_in glass_1 top_cabinet_3)
(stored cutting_board_1)
(stored ketchup_bottle_1)
(stored cup_1)
(stored ground_coffee_1)
(stored hotsauce_bottle_1)
(stored_in bowl_7 bottom_cabinet_3)
(stored_in beer_can_1 fridge_1)
(stored worcestershire_sauce_bottle_1)
(stored_in ketchup_bottle_1 top_cabinet_2)
(stored toast_1)
(stored_in large_bowl_1 bottom_cabinet_3)
(stored_in sausage_1 fridge_1)
(stored strawberry_3)
(stored_in wine_glass_2 top_cabinet_3)
(stored_in tea_pot_cap_1 bottom_cabinet_1)
(stored dough_1)
(stored_in wine_glass_1 top_cabinet_3)
(stored_in small_plate_6 fridge_1)
(stored can_opener_1)
(stored_in tea_pot_cap_1 tea_pot_1)
(stored_in ground_coffee_1 bottom_cabinet_1)
(stored_in bowl_6 bowl_7)
(stored strawberry_2)
(stored kiwi_1)
(stored wine_glass_2)
(stored_in baking_paper_1 bottom_cabinet_1)
(stored flat_dough_1)
(stored_in espresso_cup_2 top_cabinet_3)
(stored fork_2)
(stored sausage_1)
(stored grater_1)
(stored_in egg_cup_glass_2 top_cabinet_3)
(stored_in espresso_cup_1 top_cabinet_3)
(stored cucumber_1)
(stored_in balsamic_1 top_cabinet_2)
(stored_in pot_top_1 bottom_cabinet_2)
(stored beer_can_2)
(stored_in bowl_9 bottom_cabinet_3)
(stored_in deep_pan_2 bottom_cabinet_2)
(stored saucepan_1)
(stored blueberries_2)
(stored knife_food_1)
(stored strawberry_4)
(stored mug_2)
(stored_in ladle_2 drawer_1)
(stored_in blueberries_2 bowl_1)
(stored milk_1)
(stored baguette_2)
(stored deep_pan_2)
(stored toast_4)
(stored egg_3)
(stored_in can_2 top_cabinet_1)
(stored_in can_3 top_cabinet_1)
(stored_in saucer_1 top_cabinet_3)
(stored blueberries_1)
(stored cup_2)
(stored bowl_2)
(stored_in pot_2 bottom_cabinet_2)
(stored detergent_1)
(stored milkcap_1)
(stored_in toast_2 top_cabinet_1)
(stored_in glass_2 top_cabinet_3)
(stored knife_large_1)
(stored butter_1)
(stored big_plate_2)
(stored egg_2)
(stored glass_2)
(stored rice_vinegar_1)
(stored_in bowl_2 fridge_1)
(stored_in pepper_vegetable_1 fridge_1)
(stored tomato_1)
(stored soy_sauce_1)
(stored_in pot_top_2 bottom_cabinet_2)
(stored_in sausage_2 fridge_1)
(stored bowl_8)
(stored_in pear_2 fridge_1)
(stored_in knife_food_1 drawer_1)
(stored_in can_opener_1 drawer_1)
(stored bowl_5)
(stored_in lemon_half_1 fridge_1)
(stored_in mushroom_1 fridge_1)
(stored_in bowl_6 bottom_cabinet_3)
(stored_in strawberry_2 fridge_1)
(stored_in milk_1 fridge_1)
(stored_in strawberry_4 fridge_1)
(stored_in egg_cup_glass_1 top_cabinet_3)
(stored_in potato_3 top_cabinet_2)
(stored_in bowl_8 bottom_cabinet_3)
(stored blender_cap_1)
(stored_in cutting_board_1 drawer_1)
(stored small_plate_6)
(stored espresso_cup_2)
(stored onion_1)
(stored_in avocado_1 fridge_1)
(stored balsamic_1)
(stored tea_cup_2)
(stored_in rolling_pin_1 drawer_1)
(stored_in fork_2 drawer_1)
(stored strawberry_1)
(stored olive_oil_1)
(stored_in cup_1 top_cabinet_3)
(stored_in cucumber_1 fridge_1)
(stored cheese_1)
(stored bowl_3)
(stored_in onion_2 top_cabinet_2)
(stored_in potato_2 top_cabinet_2)
(stored sesame_oil_1)
(stored_in pot_1 bottom_cabinet_2)
(stored lemon_half_1)
(stored_in kiwi_1 fridge_1)
(stored_in dough_1 fridge_1)
(stored mustard_bottle_1)
(stored_in cleaver_1 drawer_1)
(stored_in sesame_oil_1 top_cabinet_2)
(stored_in big_plate_1 top_cabinet_3)
(stored wine_glass_1)
(stored fork_1)
(stored_in bowl_3 bottom_cabinet_3)
(stored_in knife_large_1 drawer_1)
(stored_in tea_cup_2 top_cabinet_3)
(stored tea_pot_cap_1)
(stored_in mug_1 top_cabinet_3)
(stored_in deep_pan_1 bottom_cabinet_2)
(stored_in large_bowl_2 bottom_cabinet_3)
(stored_in pear_1 fridge_1)
(stored_in egg_2 fridge_1)
(stored_in banana_1 fridge_1)
(stored ladle_1)
(stored_in bowl_5 bottom_cabinet_3)
(stored_in knife_sharpener_1 drawer_1)
(stored_in spoon_1 drawer_1)
(stored banana_2)
(stored_in garlic_2 top_cabinet_2)
(stored_in potato_1 top_cabinet_2)
(stored_in blender_cap_1 blender_body_1)
(stored_in salad_1 fridge_1)
(stored_in saucer_2 top_cabinet_3)
(stored egg_cup_glass_2)
(stored_in glass_4 top_cabinet_3)
(stored_in onion_1 top_cabinet_2)
(stored_in strawberry_1 fridge_1)
(stored_in lime_half_1 fridge_1)
(stored rolling_pin_1)
(stored kitchen_knife_1)
(stored_in blueberries_2 fridge_1)
(stored_in small_plate_5 top_cabinet_1)
(stored_in bread_loaf_1 top_cabinet_1)
(stored_in lime_1 fridge_1)
(stored whisk_1)
(stored pepper_vegetable_1)
(stored_in toast_5 top_cabinet_1)
(stored sausage_2)
(stored apple_2)
(stored_in can_1 top_cabinet_1)
(stored bowl_4)
(stored zucchini_1)
(stored front_peeler_1)
(stored knife_large_2)
(stored_in big_spoon_1 drawer_1)
(stored_in knife_1 drawer_1)
(stored_in beer_bottle_1 fridge_1)
(stored baking_paper_1)
(stored can_2)
(stored big_spoon_1)
(stored pear_1)
(stored_in detergent_1 kitchen_sink_1)
(stored bowl_6)
(stored_in grater_1 drawer_1)
(stored small_plate_5)
(stored_in glass_5 top_cabinet_3)
(stored orange_2)
(stored_in cup_2 top_cabinet_3)
(stored_in mug_2 top_cabinet_3)
(stored_in tray_1 stove_1)
(stored_in egg_3 fridge_1)
(stored toast_3)
(stored orange_1)
(stored large_bowl_1)
(stored_in mushroom_3 fridge_1)
(stored cap_opener_1)
(stored_in pineapple_1 fridge_1)
(stored handsoap_1)
(stored_in saucepan_big_1 bottom_cabinet_2)
(stored bun_1)
(stored mushroom_2)
(stored dishsoap_1)
(stored_in bowl_9 bowl_8)
(stored mushroom_3)
(stored beer_can_1)
(stored_in mustard_bottle_1 top_cabinet_2)
(stored_in deep_pan_1 deep_pan_2)
(stored_in egg_1 fridge_1)
(stored_in apple_2 fridge_1)
(stored pot_top_2)
(stored_in whisk_1 drawer_1)
(stored_in lemon_1 fridge_1)
(stored_in strawberry_3 fridge_1)
(stored big_plate_1)
(stored_in cap_opener_1 drawer_1)
(stored_in blueberries_1 fridge_1)
(stored pineapple_1)
(stored_in orange_2 fridge_1)
(stored bread_loaf_1)
(stored_in faucet_1 kitchen_sink_1)
(stored lemon_1)
(stored_in butter_1 fridge_1)
(stored bowl_7)
(stored glass_5)
(stored knife_1)
(stored_in fork_1 drawer_1)
(stored_in banana_2 fridge_1)
(stored bowl_9)
(stored pot_2)
(stored can_3)
(stored carrot_1)
(stored pot_1)
(stored_in handsoap_1 kitchen_sink_1)
(stored orange_half_1)
(stored mushroom_1)
(stored_in bun_1 top_cabinet_1)
(stored_in big_plate_2 top_cabinet_3)
(stored_in orange_1 fridge_1)
(stored_in cheese_1 fridge_1)
(stored spoon_1)
(stored garlic_1)
(stored cleaver_1)
(stored_in baguette_1 top_cabinet_1)
(stored_in knife_large_2 drawer_1)
(stored faucet_1)
(stored egg_cup_glass_1)
(stored_in zucchini_1 fridge_1)
(stored tray_1)
(stored_in milkcap_1 fridge_1)
(stored potato_3)
(stored can_1)
(stored_in olive_oil_1 top_cabinet_2)
(stored garlic_2)
(stored_in dishsoap_1 kitchen_sink_1)
(stored_in toast_1 top_cabinet_1)
(stored potato_1)
(stored_in bowl_8 bowl_9)
(stored pot_top_1)
(stored lime_half_1)
(stored large_bowl_2)
(stored_in salad_3 fridge_1)
(stored_in mushroom_2 fridge_1)
(stored avocado_1)
(stored_in soy_sauce_1 top_cabinet_2)
(stored saucer_1)
(stored saucepan_big_1)
(stored_in salad_2 fridge_1)
(stored glass_1)
(stored_in bowl_4 bottom_cabinet_3)
(stored_in tea_cup_1 top_cabinet_3)
(stored_in glass_3 top_cabinet_3)
(stored_in broccoli_1 fridge_1)
(stored_in flat_dough_1 fridge_1)
(stored_in tomato_1 fridge_1)
(stored_in rice_vinegar_1 top_cabinet_2)
(stored_in kitchen_knife_1 drawer_1)
(stored_in toast_4 top_cabinet_1)
(stored pear_2)
(stored cheese_2)
(stored baguette_1)
(stored_in worcestershire_sauce_bottle_1 top_cabinet_2)
(stored_in orange_half_1 fridge_1)
(stored_in ladle_1 drawer_1)
(stored broccoli_1)
(stored salad_3)
(stored glass_4)
(stored onion_2)
(stored salad_2)
(stored_in front_peeler_1 drawer_1)
(stored toast_2)
(stored glass_3)
(stored_in baguette_2 top_cabinet_1)
(stored tea_cup_1)
(stored banana_1)
(stored knife_sharpener_1)
(stored_in cheese_2 fridge_1)
(stored_in hotsauce_bottle_1 top_cabinet_2)
(stored potato_2)
(stored beer_bottle_1)
(stored_in garlic_1 top_cabinet_2)
(stored mug_1)
(stored egg_1)
(stored saucer_2)
(stored toast_5)
(stored_in beer_can_2 fridge_1)
(stored espresso_cup_1)
(stored_in saucepan_1 bottom_cabinet_2)
    <insert_class_memberships>
)
(:goal (and
(goaldummy)
))
)
